export interface FontPair {
  id: string;
  label: string;
  mood: string;
  heading: string;
  body: string;
  headingWeight: string;
  bodyWeight: string;
  googleQuery: string;
  headingCase?: "none" | "upper";
  headingTracking: string;
}

// Real, deliberately-paired typography. Each pair carries its own voice —
// swapping the pair should visibly change the personality of the page.
export const FONT_PAIRS: FontPair[] = [
  {
    id: "editorial",
    label: "Editorial",
    mood: "Serio, con autoridad. Revistas, consultoría, despachos.",
    heading: "'Playfair Display', Georgia, serif",
    body: "'Source Sans 3', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "Playfair+Display:wght@500;700;900&family=Source+Sans+3:wght@400;600",
    headingTracking: "-0.02em",
  },
  {
    id: "modern",
    label: "Moderno",
    mood: "Limpio y técnico. Software, agencias, startups.",
    heading: "'Space Grotesk', -apple-system, sans-serif",
    body: "'Inter', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600",
    headingTracking: "-0.03em",
  },
  {
    id: "warm",
    label: "Cálido",
    mood: "Cercano y humano. Restaurantes, bienestar, artesanal.",
    heading: "'Fraunces', Georgia, serif",
    body: "'Nunito Sans', -apple-system, sans-serif",
    headingWeight: "600",
    bodyWeight: "400",
    googleQuery: "Fraunces:opsz,wght@9..144,500;9..144,700&family=Nunito+Sans:wght@400;600",
    headingTracking: "-0.01em",
  },
  {
    id: "bold",
    label: "Impacto",
    mood: "Fuerte y directo. Gimnasios, eventos, deportes.",
    heading: "'Archivo Black', Impact, sans-serif",
    body: "'Archivo', -apple-system, sans-serif",
    headingWeight: "400",
    bodyWeight: "400",
    googleQuery: "Archivo+Black&family=Archivo:wght@400;500;600",
    headingCase: "upper",
    headingTracking: "-0.01em",
  },
  {
    id: "refined",
    label: "Refinado",
    mood: "Elegante y espacioso. Lujo, moda, inmobiliaria.",
    heading: "'Cormorant Garamond', Georgia, serif",
    body: "'Jost', -apple-system, sans-serif",
    headingWeight: "600",
    bodyWeight: "300",
    googleQuery: "Cormorant+Garamond:wght@400;600;700&family=Jost:wght@300;400;500",
    headingTracking: "0.01em",
  },
  {
    id: "friendly",
    label: "Amigable",
    mood: "Accesible y claro. Comercio, servicios, salud.",
    heading: "'Poppins', -apple-system, sans-serif",
    body: "'Karla', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "Poppins:wght@500;600;700&family=Karla:wght@400;500;600",
    headingTracking: "-0.02em",
  },
  {
    id: "brutalist",
    label: "Brutalista",
    mood: "Crudo, sin adornos, muy contemporáneo. Streetwear, arte, música.",
    heading: "'Anton', Impact, sans-serif",
    body: "'Work Sans', -apple-system, sans-serif",
    headingWeight: "400",
    bodyWeight: "400",
    googleQuery: "Anton&family=Work+Sans:wght@400;500;600",
    headingCase: "upper",
    headingTracking: "0em",
  },
  {
    id: "geometric",
    label: "Geométrico",
    mood: "Preciso y matemático. Fintech, arquitectura, ingeniería.",
    heading: "'Sora', -apple-system, sans-serif",
    body: "'IBM Plex Sans', -apple-system, sans-serif",
    headingWeight: "600",
    bodyWeight: "400",
    googleQuery: "Sora:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500",
    headingTracking: "-0.02em",
  },
  {
    id: "technical",
    label: "Técnico",
    mood: "Preciso, tipo terminal. Software, datos, ciberseguridad.",
    heading: "'JetBrains Mono', 'Courier New', monospace",
    body: "'Inter', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "JetBrains+Mono:wght@500;700&family=Inter:wght@400;500",
    headingTracking: "-0.01em",
  },
  {
    id: "vintage",
    label: "Vintage",
    mood: "Nostálgico, con carácter. Cafeterías, barberías, marcas artesanales.",
    heading: "'Abril Fatface', Georgia, serif",
    body: "'Lato', -apple-system, sans-serif",
    headingWeight: "400",
    bodyWeight: "400",
    googleQuery: "Abril+Fatface&family=Lato:wght@400;700",
    headingTracking: "-0.01em",
  },
  {
    id: "playful",
    label: "Juguetón",
    mood: "Redondeado y divertido. Niños, juguetes, apps casuales.",
    heading: "'Baloo 2', -apple-system, sans-serif",
    body: "'Mulish', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "Baloo+2:wght@600;700;800&family=Mulish:wght@400;600",
    headingTracking: "-0.01em",
  },
  {
    id: "luxury",
    label: "Lujo",
    mood: "Alta costura, minimalista y frío. Joyería, hoteles cinco estrellas.",
    heading: "'Bodoni Moda', Georgia, serif",
    body: "'Montserrat', -apple-system, sans-serif",
    headingWeight: "500",
    bodyWeight: "300",
    googleQuery: "Bodoni+Moda:wght@400;500;700&family=Montserrat:wght@300;400;500",
    headingCase: "upper",
    headingTracking: "0.08em",
  },
  {
    id: "condensed",
    label: "Condensado",
    mood: "Denso y urbano. Noticias, deportes, retail rápido.",
    heading: "'Oswald', 'Arial Narrow', sans-serif",
    body: "'Public Sans', -apple-system, sans-serif",
    headingWeight: "600",
    bodyWeight: "400",
    googleQuery: "Oswald:wght@500;600;700&family=Public+Sans:wght@400;500",
    headingCase: "upper",
    headingTracking: "0.01em",
  },
  {
    id: "handwritten",
    label: "Manuscrito",
    mood: "Personal y cálido, con un toque de firma a mano. Repostería, floristerías.",
    heading: "'Caveat', cursive",
    body: "'Quicksand', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "500",
    googleQuery: "Caveat:wght@600;700&family=Quicksand:wght@400;500;600",
    headingTracking: "0em",
  },
  {
    id: "corporate",
    label: "Corporativo",
    mood: "Serio y confiable, sin sorpresas. Bancos, seguros, legal.",
    heading: "'Libre Franklin', -apple-system, sans-serif",
    body: "'Libre Franklin', -apple-system, sans-serif",
    headingWeight: "700",
    bodyWeight: "400",
    googleQuery: "Libre+Franklin:wght@400;500;700;800",
    headingTracking: "-0.01em",
  },
  {
    id: "editorial-sans",
    label: "Editorial Sans",
    mood: "Revista moderna sin serifa. Cultura, medios, publicaciones digitales.",
    heading: "'Fraunces', Georgia, serif",
    body: "'Archivo', -apple-system, sans-serif",
    headingWeight: "900",
    bodyWeight: "400",
    googleQuery: "Fraunces:opsz,wght@9..144,700;9..144,900&family=Archivo:wght@400;500",
    headingTracking: "-0.03em",
  },
  {
    id: "minimal-jp",
    label: "Minimalista",
    mood: "Silencioso y espacioso. Estudios de diseño, wellness, arquitectura.",
    heading: "'Zen Old Mincho', Georgia, serif",
    body: "'Noto Sans', -apple-system, sans-serif",
    headingWeight: "500",
    bodyWeight: "300",
    googleQuery: "Zen+Old+Mincho:wght@500;600&family=Noto+Sans:wght@300;400",
    headingTracking: "0.02em",
  },
];

export function getFontPair(id: string): FontPair {
  return FONT_PAIRS.find((f) => f.id === id) ?? FONT_PAIRS[1];
}
