/**
 * "Diseño original" demos: the source page's own HTML and CSS, served as-is
 * instead of being rebuilt from `Section` data.
 *
 * Every other demo in this CRM is generated by `render.ts` from a typed,
 * validated config — that is what makes it editable, and it is also what
 * makes it impossible to reproduce a page pixel-for-pixel: a re-render can
 * only be as faithful as the section model is expressive. When the ask is
 * fidelity — "it needs to look exactly like this" — the section model is the
 * wrong tool, and the honest answer is to keep the original markup.
 *
 * This file is deliberately the *isomorphic* half of verbatim mode — pure
 * string operations, safe to import from anything, including client
 * components. The real sanitizer lives in `verbatimSanitize.ts` instead of
 * here on purpose: `render.ts` (which needs `buildVerbatimDocument`) is
 * imported directly by `DemoBuilder.tsx` for its live preview iframe, which
 * makes render.ts part of the browser bundle. `sanitize-html` — the actual
 * allowlist pass — is a Node-oriented package with no business shipping to a
 * browser, so it stays in a file nothing client-side ever imports.
 */

/** Output caps the real sanitizer (see verbatimSanitize.ts) enforces. */
export const MAX_VERBATIM_HTML = 500_000;
export const MAX_VERBATIM_CSS = 300_000;

/**
 * A fast, DOM-free backstop for the one place verbatim HTML gets rendered
 * without going through `validateDemoConfig()` first: the demo builder's own
 * live preview iframe reads straight from in-memory editor state (see
 * `DemoBuilder.tsx`), not from a freshly re-validated config. That state can
 * only ever hold what was already sanitized on its way into the database, so
 * this is not the real filter — it is cheap insurance against a future write
 * path that forgets to be. Cannot replace `sanitizeVerbatimHtml`; it has none
 * of its tag/attribute knowledge, only enough pattern-matching to neutralize
 * a `<script>` or an `on*=` handler if one ever gets this far.
 */
export function stripDangerousHtml(html: string): string {
  if (typeof html !== "string") return "";
  return html
    .replace(/<script\b[\s\S]*?<\/script\s*>/gi, "")
    .replace(/<script\b[^>]*>/gi, "")
    .replace(/<iframe\b[\s\S]*?<\/iframe\s*>/gi, "")
    .replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, "")
    .replace(/javascript\s*:/gi, "")
    .replace(/<base\b[^>]*>/gi, "");
}

/**
 * Wraps already-sanitized html + css into a standalone document.
 *
 * Deliberately does no sanitizing of its own — the content is trusted to
 * already be clean by the time it reaches here (either freshly sanitized at
 * import time, or read back out of the database where it was stored clean).
 * That makes this safe to call from a client component too: it is pure
 * string assembly, so the demo builder's live preview can use the exact same
 * function without pulling `sanitize-html` (a Node-oriented package) into
 * the browser bundle.
 */
export function buildVerbatimDocument(html: string, css: string): string {
  const body = typeof html === "string" ? html : "";
  const styleBlock = css ? `<style>${css}</style>` : "";

  // The stored value is already a full <html>…</html> document (captured
  // from document.documentElement.outerHTML, or assembled the same way for
  // non-rendered sources) — inject our captured stylesheet right before
  // </head> so it applies after the page's own inline <style>/<link> tags
  // rather than being overridden by them.
  if (/<head[\s>]/i.test(body) && /<\/head>/i.test(body)) {
    return `<!DOCTYPE html>\n${body.replace(/<\/head>/i, `${styleBlock}</head>`)}`;
  }
  // No recognisable <head> (a fragment rather than a full document, e.g. a
  // hand-pasted snippet) — wrap it properly instead of guessing where to
  // splice.
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${styleBlock}</head><body>${body}</body></html>`;
}

/**
 * Marker attribute on everything this file injects for editing, so it can be
 * stripped back out before the edited markup is ever stored — the same rule
 * `render.ts` follows for its Section-mode `data-text`/`contenteditable`
 * scaffolding, applied to a page that has no Sections to hang it on.
 */
const INJECT_ATTR = "data-oliwan-inject";

/**
 * "text": whole-page contentEditable + drag-reorder of top-level `<body>`
 *   blocks. "menu": the same, scoped to the page's own `<nav>` links, plus
 *   add/remove and a URL prompt. "style": click any element — header,
 *   footer, a card, a button, the logo — to edit its inline style (or swap
 *   its image) without touching anything else on the page.
 *
 * None of these invent a block or component model for arbitrary HTML; each
 * one edits the real DOM node a click actually lands on. That's the honest
 * ceiling for a page whose whole point is being the source's own markup.
 */
export type VerbatimEditMode = "text" | "menu" | "style";
const EDIT_SCRIPT = `(function(){
  var MODE = window.__oliwanMode || 'text';
  function snapshot(){
    var clone = document.documentElement.cloneNode(true);
    var junk = clone.querySelectorAll('[${INJECT_ATTR}]');
    for (var i = 0; i < junk.length; i++) junk[i].parentNode.removeChild(junk[i]);
    var draggable = clone.querySelectorAll('[draggable]');
    for (var j = 0; j < draggable.length; j++) draggable[j].removeAttribute('draggable');
    var over = clone.querySelectorAll('.oliwan-drag-over');
    for (var k = 0; k < over.length; k++) over[k].classList.remove('oliwan-drag-over');
    var marked = clone.querySelectorAll('.oliwan-hover, .oliwan-selected');
    for (var m = 0; m < marked.length; m++) marked[m].classList.remove('oliwan-hover', 'oliwan-selected');
    return '<!DOCTYPE html>\\n' + clone.outerHTML;
  }
  function notify(){
    try { parent.postMessage({ source: 'oliwan-verbatim', type: 'change', html: snapshot() }, '*'); } catch (err) {}
  }
  var timer;
  function debouncedNotify(){ clearTimeout(timer); timer = setTimeout(notify, 400); }

  function enableDrag(el, onDrop){
    el.setAttribute('draggable', 'true');
    el.addEventListener('dragstart', function (e) { e.stopPropagation(); onDrop.dragged = el; });
    el.addEventListener('dragover', function (e) { e.preventDefault(); e.stopPropagation(); el.classList.add('oliwan-drag-over'); });
    el.addEventListener('dragleave', function (e) { e.stopPropagation(); el.classList.remove('oliwan-drag-over'); });
    el.addEventListener('drop', function (e) {
      e.preventDefault();
      e.stopPropagation();
      el.classList.remove('oliwan-drag-over');
      var dragged = onDrop.dragged;
      if (!dragged || dragged === el || !el.parentNode || dragged.parentNode !== el.parentNode) return;
      var siblings = Array.prototype.slice.call(el.parentNode.children);
      var before = siblings.indexOf(dragged) < siblings.indexOf(el);
      el.parentNode.insertBefore(dragged, before ? el.nextSibling : el);
      onDrop.dragged = null;
      notify();
    });
  }

  if (MODE === 'text') {
    document.body.setAttribute('contenteditable', 'true');
    document.body.addEventListener('input', debouncedNotify);
    document.body.addEventListener('blur', notify, true);

    var blockDrop = { dragged: null };
    var blocks = Array.prototype.slice.call(document.body.children);
    blocks.forEach(function (el) {
      if (el.hasAttribute('${INJECT_ATTR}')) return;
      enableDrag(el, blockDrop);
    });
  }

  if (MODE === 'menu') {
    var nav = document.querySelector('nav') || document.querySelector('[role="navigation"]') || document.querySelector('header');
    if (nav) {
      var navDrop = { dragged: null };
      var links = Array.prototype.slice.call(nav.querySelectorAll('a'));
      links.forEach(function (a) {
        a.setAttribute('contenteditable', 'true');
        a.addEventListener('input', debouncedNotify);
        a.addEventListener('blur', notify, true);
        a.addEventListener('click', function (e) { e.preventDefault(); });
        a.addEventListener('dblclick', function (e) {
          e.preventDefault();
          var next = window.prompt('URL de este enlace:', a.getAttribute('href') || '');
          if (next !== null) { a.setAttribute('href', next); notify(); }
        });

        var del = document.createElement('span');
        del.setAttribute('${INJECT_ATTR}', '1');
        del.className = 'oliwan-nav-del';
        del.textContent = '\\u00d7';
        del.title = 'Eliminar este enlace';
        del.addEventListener('click', function (e) {
          e.preventDefault();
          e.stopPropagation();
          var host = a.closest('li') || a;
          if (host.parentNode) host.parentNode.removeChild(host);
          notify();
        });
        a.insertAdjacentElement('afterend', del);

        var item = a.closest('li') || a;
        enableDrag(item, navDrop);
      });

      var addBtn = document.createElement('button');
      addBtn.type = 'button';
      addBtn.setAttribute('${INJECT_ATTR}', '1');
      addBtn.className = 'oliwan-nav-add';
      addBtn.textContent = '+ agregar enlace';
      addBtn.addEventListener('click', function () {
        var label = window.prompt('Texto del enlace:');
        if (!label) return;
        var href = window.prompt('URL:', '#') || '#';
        var proto = links.length ? links[links.length - 1] : null;
        var a2 = proto ? proto.cloneNode(false) : document.createElement('a');
        a2.textContent = label;
        a2.setAttribute('href', href);
        a2.removeAttribute('${INJECT_ATTR}');
        var protoHost = proto ? (proto.closest('li') || proto) : null;
        if (protoHost && protoHost.tagName === 'LI' && protoHost.parentNode) {
          var li = document.createElement('li');
          li.appendChild(a2);
          protoHost.parentNode.appendChild(li);
        } else if (protoHost && protoHost.parentNode) {
          protoHost.parentNode.appendChild(a2);
        } else {
          nav.appendChild(a2);
        }
        notify();
      });
      nav.appendChild(addBtn);
    }
  }

  if (MODE === 'style') {
    function pathOf(el){
      var path = [];
      var node = el;
      while (node && node !== document.body) {
        var p = node.parentElement;
        if (!p) break;
        path.unshift(Array.prototype.indexOf.call(p.children, node));
        node = p;
      }
      return path;
    }
    function elAt(path){
      var node = document.body;
      for (var i = 0; i < path.length; i++) {
        if (!node || !node.children[path[i]]) return null;
        node = node.children[path[i]];
      }
      return node;
    }

    var hovered = null;
    document.body.addEventListener('mouseover', function (e) {
      var el = e.target;
      if (!el || el === document.body || el.hasAttribute('${INJECT_ATTR}')) return;
      if (hovered && hovered !== el) hovered.classList.remove('oliwan-hover');
      hovered = el;
      el.classList.add('oliwan-hover');
    });
    document.body.addEventListener('mouseout', function () {
      if (hovered) { hovered.classList.remove('oliwan-hover'); hovered = null; }
    });
    document.body.addEventListener('click', function (e) {
      var el = e.target;
      if (!el || el === document.body || el.hasAttribute('${INJECT_ATTR}')) return;
      e.preventDefault();
      e.stopPropagation();
      var prevSel = document.querySelector('.oliwan-selected');
      if (prevSel) prevSel.classList.remove('oliwan-selected');
      el.classList.add('oliwan-selected');
      try {
        parent.postMessage({
          source: 'oliwan-verbatim',
          type: 'select',
          path: pathOf(el),
          tag: el.tagName.toLowerCase(),
          style: el.getAttribute('style') || '',
          isImg: el.tagName === 'IMG',
          src: el.tagName === 'IMG' ? el.getAttribute('src') : null
        }, '*');
      } catch (err) {}
    }, true);

    window.addEventListener('message', function (e) {
      var d = e.data;
      if (!d || d.source !== 'oliwan-editor-verbatim') return;
      var el = elAt(d.path || []);
      if (!el) return;
      if (d.type === 'apply-style') {
        el.setAttribute('style', d.style || '');
        notify();
      } else if (d.type === 'apply-src' && el.tagName === 'IMG') {
        el.setAttribute('src', d.src || '');
        notify();
      }
    });
  }
})();`;

const EDIT_STYLE = `[draggable="true"]{cursor:grab;}
[draggable="true"]:hover{outline:2px dashed rgba(99,102,241,.5);outline-offset:2px;}
.oliwan-drag-over{outline:2px solid #6366f1 !important;outline-offset:2px;}
[contenteditable="true"]:focus{outline:none;}
.oliwan-nav-del{display:inline-block;margin-left:4px;padding:0 5px;font:700 13px/1.4 sans-serif;color:#ef4444;cursor:pointer;user-select:none;border-radius:3px;}
.oliwan-nav-del:hover{background:rgba(239,68,68,.15);}
.oliwan-nav-add{margin-left:10px;padding:2px 10px;font:600 12px sans-serif;border:1px dashed #6366f1;color:#6366f1;background:transparent;border-radius:5px;cursor:pointer;}
.oliwan-hover{outline:2px dashed rgba(99,102,241,.6) !important;outline-offset:1px;cursor:pointer;}
.oliwan-selected{outline:2px solid #6366f1 !important;outline-offset:1px;}`;

/**
 * Same document as `buildVerbatimDocument`, plus an editing bridge that only
 * ever lives inside the builder's preview iframe — never persisted, and
 * stripped back out (see `snapshot()` above) before any edit is reported
 * back to the parent page via `postMessage`.
 */
export function buildVerbatimEditDocument(html: string, css: string, mode: VerbatimEditMode = "text"): string {
  const doc = buildVerbatimDocument(html, css);
  const injected = `<script ${INJECT_ATTR}="1">window.__oliwanMode=${JSON.stringify(mode)};</script><style ${INJECT_ATTR}="1">${EDIT_STYLE}</style><script ${INJECT_ATTR}="1">${EDIT_SCRIPT}</script>`;
  if (/<\/body>/i.test(doc)) return doc.replace(/<\/body>/i, `${injected}</body>`);
  return `${doc}${injected}`;
}

const NAV_BLOCK = /<nav\b[\s\S]*?<\/nav>/i;
const HEADER_BLOCK = /<header\b[\s\S]*?<\/header>/i;

/** Whether a page has a `<nav>` (or a `<header>` to fall back to) worth
 *  showing a "Menú" editor for. */
export function hasNavBlock(html: string): boolean {
  return NAV_BLOCK.test(html ?? "") || HEADER_BLOCK.test(html ?? "");
}

/**
 * Multi-page verbatim sites usually repeat the same nav markup on every
 * page — editing it once and re-editing it four more times by hand is
 * exactly the kind of busywork this builder exists to avoid. Lifts the
 * `<nav>` (or `<header>`, if that's what has the links) out of `sourceHtml`
 * and swaps it into the same spot in `targetHtml`, leaving everything else
 * about the target page untouched.
 */
export function replaceNavBlock(targetHtml: string, sourceHtml: string): string {
  const block = (h: string) => {
    const nav = NAV_BLOCK.exec(h);
    if (nav) return { text: nav[0], re: NAV_BLOCK };
    const header = HEADER_BLOCK.exec(h);
    return header ? { text: header[0], re: HEADER_BLOCK } : null;
  };
  const src = block(sourceHtml ?? "");
  const dst = block(targetHtml ?? "");
  if (!src || !dst) return targetHtml;
  return targetHtml.replace(dst.re, src.text);
}

/** Turns an inline `style="a: b; c: d"` attribute into a plain lookup —
 *  just enough to read and rewrite the handful of properties the style
 *  panel exposes, without needing a real CSS parser for a single element's
 *  attribute. */
export function parseInlineStyle(style: string): Record<string, string> {
  const out: Record<string, string> = {};
  (style ?? "").split(";").forEach((decl) => {
    const idx = decl.indexOf(":");
    if (idx === -1) return;
    const key = decl.slice(0, idx).trim().toLowerCase();
    const value = decl.slice(idx + 1).trim();
    if (key && value) out[key] = value;
  });
  return out;
}

export function serializeInlineStyle(props: Record<string, string>): string {
  return Object.entries(props)
    .filter(([, v]) => v)
    .map(([k, v]) => `${k}: ${v};`)
    .join(" ");
}

export interface CssColorVar {
  name: string;
  value: string;
  /** Only "hex" gets a real color-swatch input; rgb()/hsl() etc. are edited as text. */
  kind: "hex" | "other";
}

const ROOT_BLOCK = /:root\s*{([^}]*)}/i;
const HEX_COLOR = /^#(?:[0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;
const COLOR_LIKE = /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\()/i;

/** Color custom properties declared in the page's own `:root` block — the
 *  real palette of a site that uses CSS variables, which is how most modern
 *  hand-built or generated sites theme themselves. */
export function extractRootColorVars(css: string): CssColorVar[] {
  const block = ROOT_BLOCK.exec(css ?? "");
  if (!block) return [];
  const out: CssColorVar[] = [];
  const re = /(--[\w-]+)\s*:\s*([^;]+);/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block[1]))) {
    const value = m[2].trim();
    if (COLOR_LIKE.test(value)) out.push({ name: m[1], value, kind: HEX_COLOR.test(value) ? "hex" : "other" });
  }
  return out;
}

/** Rewrites one `--var: value;` declaration inside `:root`, leaving
 *  everything else in the stylesheet untouched. */
export function setRootColorVar(css: string, name: string, value: string): string {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const decl = new RegExp(`(${escaped}\\s*:\\s*)[^;]+;`);
  if (decl.test(css)) return css.replace(decl, `$1${value};`);
  return css;
}
