/**
 * "Diseño original" demos: the source page's own HTML and CSS, served as-is
 * instead of being rebuilt from `Section` data.
 *
 * Every other demo in this CRM is generated by `render.ts` from a typed,
 * validated config — that is what makes it editable, and it is also what
 * makes it impossible to reproduce a page pixel-for-pixel: a re-render can
 * only be as faithful as the section model is expressive. When the ask is
 * fidelity — "it needs to look exactly like this" — the section model is the
 * wrong tool, and the honest answer is to keep the original markup.
 *
 * This file is deliberately the *isomorphic* half of verbatim mode — pure
 * string operations, safe to import from anything, including client
 * components. The real sanitizer lives in `verbatimSanitize.ts` instead of
 * here on purpose: `render.ts` (which needs `buildVerbatimDocument`) is
 * imported directly by `DemoBuilder.tsx` for its live preview iframe, which
 * makes render.ts part of the browser bundle. `sanitize-html` — the actual
 * allowlist pass — is a Node-oriented package with no business shipping to a
 * browser, so it stays in a file nothing client-side ever imports.
 */

/** Output caps the real sanitizer (see verbatimSanitize.ts) enforces. */
export const MAX_VERBATIM_HTML = 500_000;
export const MAX_VERBATIM_CSS = 300_000;

/**
 * A fast, DOM-free backstop for the one place verbatim HTML gets rendered
 * without going through `validateDemoConfig()` first: the demo builder's own
 * live preview iframe reads straight from in-memory editor state (see
 * `DemoBuilder.tsx`), not from a freshly re-validated config. That state can
 * only ever hold what was already sanitized on its way into the database, so
 * this is not the real filter — it is cheap insurance against a future write
 * path that forgets to be. Cannot replace `sanitizeVerbatimHtml`; it has none
 * of its tag/attribute knowledge, only enough pattern-matching to neutralize
 * a `<script>` or an `on*=` handler if one ever gets this far.
 */
export function stripDangerousHtml(html: string): string {
  if (typeof html !== "string") return "";
  return html
    .replace(/<script\b[\s\S]*?<\/script\s*>/gi, "")
    .replace(/<script\b[^>]*>/gi, "")
    .replace(/<iframe\b[\s\S]*?<\/iframe\s*>/gi, "")
    .replace(/\son\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, "")
    .replace(/javascript\s*:/gi, "")
    .replace(/<base\b[^>]*>/gi, "");
}

/**
 * Wraps already-sanitized html + css into a standalone document.
 *
 * Deliberately does no sanitizing of its own — the content is trusted to
 * already be clean by the time it reaches here (either freshly sanitized at
 * import time, or read back out of the database where it was stored clean).
 * That makes this safe to call from a client component too: it is pure
 * string assembly, so the demo builder's live preview can use the exact same
 * function without pulling `sanitize-html` (a Node-oriented package) into
 * the browser bundle.
 */
export function buildVerbatimDocument(html: string, css: string): string {
  const body = typeof html === "string" ? html : "";
  const styleBlock = css ? `<style>${css}</style>` : "";

  // The stored value is already a full <html>…</html> document (captured
  // from document.documentElement.outerHTML, or assembled the same way for
  // non-rendered sources) — inject our captured stylesheet right before
  // </head> so it applies after the page's own inline <style>/<link> tags
  // rather than being overridden by them.
  if (/<head[\s>]/i.test(body) && /<\/head>/i.test(body)) {
    return `<!DOCTYPE html>\n${body.replace(/<\/head>/i, `${styleBlock}</head>`)}`;
  }
  // No recognisable <head> (a fragment rather than a full document, e.g. a
  // hand-pasted snippet) — wrap it properly instead of guessing where to
  // splice.
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${styleBlock}</head><body>${body}</body></html>`;
}
